openapi: 3.0.0
info:
  title: Neo4j Book API
  version: 1.0.0
paths:
  /api/neo4j/books:
    get:
      tags:
        - Neo4j Book
      summary: Get all books from Neo4j
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: book_id_here
                  title: BookTitle
                  picture: BookPicture
                  summary: BookSummary
                  pages: 300
                  amount: 50
                  available_amount: 20
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/create/book:
    post:
      tags:
        - Neo4j Book
      summary: Create a new book in Neo4j
      requestBody:
        description: Book data
        required: true
        content:
          application/json:
            example:
              title: BookTitle
              picture: BookPicture
              summary: BookSummary
              pages: 300
              amount: 50
              available_amount: 20
      responses:
        '200':
          description: Book created successfully
          content:
            application/json:
              example:
                book: {}
                bookData: {}
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/update/book:
    put:
      tags:
        - Neo4j Book
      summary: Update a book in Neo4j
      requestBody:
        description: Book data
        required: true
        content:
          application/json:
            example:
              bookId: book_id_here
              title: UpdatedBookTitle
              picture: UpdatedBookPicture
              summary: UpdatedBookSummary
              pages: 320
              amount: 60
              available_amount: 30
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              example:
                book: {}
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/book/{bookId}:
    get:
      tags:
        - Neo4j Book
      summary: Get a book by ID from Neo4j
      parameters:
        - name: bookId
          in: path
          required: true
          description: Book ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: book_id_here
                title: BookTitle
                picture: BookPicture
                summary: BookSummary
                pages: 300
                amount: 50
                available_amount: 20
        '401':
          description: Unauthorized or Something went wrong

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
