openapi: 3.0.0
info:
  title: Neo4j Author API
  version: 1.0.0
paths:
  /api/neo4j/authors:
    get:
      tags:
        - Neo4j Author
      summary: Get all authors from Neo4j
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: author_id_here
                  username: AuthorUsername
                  total_books: 5
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/create/author:
    post:
      tags:
        - Neo4j Author
      summary: Create a new author in Neo4j
      security:
        - BearerAuth: []
      requestBody:
        description: Author data
        required: true
        content:
          application/json:
            example:
              username: AuthorUsername
              totalBooks: 5
      responses:
        '200':
          description: Author created successfully
          content:
            application/json:
              example:
                author: {}
                authorData: {}
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/delete/author/{id}:
    delete:
      tags:
        - Neo4j Author
      summary: Delete an author in Neo4j
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Author ID
          schema:
            type: string
      responses:
        '200':
          description: Author deleted successfully
          content:
            application/json:
              example:
                author: {}
        '401':
          description: Unauthorized or Something went wrong

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
