openapi: 3.0.0
info:
  title: Tag CRUD API
  description: CRUD operations for managing tags in Neo4j
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /neo4j/tags:
    get:
      summary: Get all tags
      tags:
        - Neo4j Tags
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - Something went wrong with getting all tags

  /neo4j/create/tag:
    post:
      summary: Create a new tag
      tags:
        - Neo4j Tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagRequest'
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - Something went wrong with creating tag

  /neo4j/update/tag:
    put:
      summary: Update a tag
      tags:
        - Neo4j Tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdateRequest'
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - Something went wrong with updating tag

components:
  schemas:
    TagRequest:
      type: object
      properties:
        title:
          type: string
        tag_description:
          type: string
        total_books:
          type: integer
      required:
        - title
        - tag_description
        - total_books

    TagUpdateRequest:
      type: object
      properties:
        title:
          type: string
        newTitle:
          type: string
        newDescription:
          type: string
      required:
        - title
        - newTitle
        - newDescription
