openapi: 3.0.0
info:
  title: Neo4j Authentication API
  description: API for user signup, login, and verification using Neo4j
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /neo4j/signup:
    post:
      summary: User signup
      tags:
        - Neo4j authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignupRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                authToken: "String"
                user:
                  user_id: "String"
                  created_at: "String"
                  is_deleted: "Boolean"
                  deleted_at: "String"
        '401':
          description: Unauthorized - Something went wrong with signup
      x-swagger-router-controller: YourControllerName
      operationId: signUp

  /neo4j/login:
    post:
      summary: User login
      tags:
        - Neo4j authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                authToken: "String"
                user:
                  user_id: "String"
                  created_at: "String"
                  is_deleted: "Boolean"
                  deleted_at: "String"
        '401':
          description: Unauthorized - Something went wrong with login
      x-swagger-router-controller: YourControllerName
      operationId: logIn

  /neo4j/verify:
    post:
      summary: Verify user with JWT token
      tags:
        - Neo4j authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyUserRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "User is verified!!"
        '401':
          description: Unauthorized - Invalid or expired token
      security:
        - BearerAuth: []
      x-swagger-router-controller: YourControllerName
      operationId: verifyUser

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    UserLoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    UserSignupRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - firstName
        - lastName
        - email
        - password

    VerifyUserRequest:
      type: object
      properties:
        authToken:
          type: string
      required:
        - authToken
