openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
paths:
  /neo4j/authors:
    get:
      summary: Get all authors
      tags:
        - Neo4j authors
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/create/author:
    post:
      summary: Create a new author
      tags:
        - Neo4j authors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                totalBooks:
                  type: integer
              required:
                - username
                - totalBooks
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/delete/author:
    delete:
      summary: Delete an author by username
      tags:
        - Neo4j authors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
