openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
paths:
  /neo4j/tags:
    get:
      summary: Get all tags
      tags:
        - Neo4j tags
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
    post:
      summary: Create a new tag
      tags:
        - Neo4j tags
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                tag_description:
                  type: string
              required:
                - title
                - tag_description
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/Onetag:
    get:
      summary: Get a single tag by tag description
      tags:
        - Neo4j tags
      parameters:
        - in: query
          name: tag_description
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/delete/tag:
    delete:
      summary: Delete a tag by title
      tags:
        - Neo4j tags
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
        
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
