openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
paths:
  /neo4j/create/user:
    post:
      summary: Create a new user
      tags:
        - Neo4j User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - firstName
                - lastName
                - email
                - password
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/users:
    get:
      summary: Get all users
      tags:
        - Neo4j User
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/update/user:
    put:
      summary: Update a user
      tags:
        - Neo4j User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/OneUser:
    get:
      summary: Get a single user by ID
      tags:
        - Neo4j User
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/deleteUser:
    delete:
      summary: Delete a user by ID
      tags:
        - Neo4j User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
