openapi: 3.0.0
info:
  title: Neo4j Library API documentation
  version: 1.0.0
  description: API documentation for Neo4j book routes in our library project
paths:
  /neo4j/books:
    get:
      summary: Get all books
      tags:
        - neo4j Books
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                - id: "12345"
                  title: "Book Title"
                  picture: "book_picture_url"
                  summary: "Book summary"
                  pages: 300
                  amount: 10
                  available_amount: 5
        '401':
          description: Unauthorized - Something went wrong with getting all books

  /neo4j/create/book:
    post:
      summary: Create a new book
      tags:
        - neo4j Books
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "New Book"
              picture: "new_book_picture_url"
              summary: "New book summary"
              pages: 200
              amount: 5
              available_amount: 5
      responses:
        '200':
          description: Successful creation
          content:
            application/json:
              example:
                book:
                  id: "54321"
                  title: "New Book"
                  picture: "new_book_picture_url"
                  summary: "New book summary"
                  pages: 200
                  amount: 5
                  available_amount: 5
                bookData:
                  id: "98765"
                  title: "New Book"
                  picture: "new_book_picture_url"
                  summary: "New book summary"
                  pages: 200
                  amount: 5
                  available_amount: 5
        '401':
          description: Unauthorized - Something went wrong with creating book

  /neo4j/update/book:
    put:
      summary: Update an existing book
      tags:
        - neo4j Books
      requestBody:
        required: true
        content:
          application/json:
            example:
              bookId: "12345"
              title: "Updated Book"
              picture: "updated_book_picture_url"
              summary: "Updated book summary"
              pages: 250
              amount: 8
              available_amount: 8
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              example:
                book:
                  id: "12345"
                  title: "Updated Book"
                  picture: "updated_book_picture_url"
                  summary: "Updated book summary"
                  pages: 250
                  amount: 8
                  available_amount: 8
        '401':
          description: Unauthorized - Something went wrong with updating book
