openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
paths:
  /neo4j/reviews:
    get:
      summary: Get all reviews
      tags:
        - Neo4j review
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/create/review:
    post:
      summary: Create a new review
      tags:
        - Neo4j review
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stars:
                  type: integer
              required:
                - stars
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
