openapi: 3.0.0
info:
  title: Neo4j Tag API
  version: 1.0.0
paths:
  /api/neo4j/tags:
    get:
      tags:
        - Neo4j Tag
      summary: Get all tags from Neo4j
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: tag_id_here
                  title: TagTitle
                  tag_description: TagDescription
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/create/tag:
    post:
      tags:
        - Neo4j Tag
      summary: Create a new tag in Neo4j
      requestBody:
        description: Tag data
        required: true
        content:
          application/json:
            example:
              title: TagTitle
              tag_description: TagDescription
      responses:
        '200':
          description: Tag created successfully
          content:
            application/json:
              example:
                tag: {}
                tagData: {}
                tagDataRelationship: {}
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/update/tag:
    put:
      tags:
        - Neo4j Tag
      summary: Update a tag in Neo4j
      requestBody:
        description: Tag data
        required: true
        content:
          application/json:
            example:
              title: ExistingTagTitle
              newTitle: UpdatedTagTitle
              newDescription: UpdatedTagDescription
      responses:
        '200':
          description: Tag updated successfully
          content:
            application/json:
              example:
                tag: {}
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/find/tag/id:
    get:
      tags:
        - Neo4j Tag
      summary: Find a tag by ID from Neo4j
      parameters:
        - name: tagId
          in: query
          required: true
          description: Tag ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: tag_id_here
                title: TagTitle
                tag_description: TagDescription
        '401':
          description: Unauthorized or Something went wrong

  /api/neo4j/delete/tag:
    delete:
      tags:
        - Neo4j Tag
      summary: Delete a tag in Neo4j
      requestBody:
        description: Tag data
        required: true
        content:
          application/json:
            example:
              title: TagTitleToDelete
      responses:
        '200':
          description: Tag deleted successfully
          content:
            application/json:
              example:
                tag: {}
        '401':
          description: Unauthorized or Something went wrong

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
