openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
paths:
  /neo4j/signup:
    post:
      summary: User Signup
      tags:
        - Neo4j Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - firstName
                - lastName
                - email
                - password
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                authToken: "your_auth_token"
                user: 
                  user_id: "user_id"
                  created_at: "timestamp"
                  is_deleted: false
                  deleted_at: null
      security:
        - BearerAuth: []
  /neo4j/login:
    post:
      summary: User Login
      tags:
        - Neo4j Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                authToken: "your_auth_token"
                user: 
                  user_id: "user_id"
                  created_at: "timestamp"
                  is_deleted: false
                  deleted_at: null
      security:
        - BearerAuth: []
  /neo4j/verify:
    post:
      summary: Verify User
      tags:
        - Neo4j Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "User is verified!!"
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
