openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
paths:
  /neo4j/books:
    get:
      summary: Get all books
      tags:
        - Neo4j books
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/create/book:
    post:
      summary: Create a new book
      tags:
        - Neo4j books
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                picture:
                  type: string
                summary:
                  type: string
                pages:
                  type: integer
                amount:
                  type: integer
                available_amount:
                  type: integer
              required:
                - title
                - picture
                - summary
                - pages
                - amount
                - available_amount
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/update/book:
    put:
      summary: Update a book
      tags:
        - Neo4j books
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bookId:
                  type: string
                title:
                  type: string
                picture:
                  type: string
                summary:
                  type: string
                pages:
                  type: integer
                amount:
                  type: integer
                available_amount:
                  type: integer
              required:
                - bookId
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
  /neo4j/oneBook:
    get:
      summary: Get a book by ID
      tags:
        - Neo4j books
      parameters:
        - name: bookId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
      security:
        - BearerAuth: []
tags:
  - name: books
    description: Operations related to books
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
