openapi: 3.0.0
info:
  title: Neo4j Authentication API
  description: API for user signup, login, and verification using Neo4j
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /neo4j/signup:
    post:
      summary: User signup
      tags:
        - Neo4j authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Neo4jSignupRequest'
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - Something went wrong with signup
      security:
        - BearerAuth: []

  /neo4j/login:
    post:
      summary: User login
      tags:
        - Neo4j authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Neo4jLoginRequest'
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - Something went wrong with login
      security:
        - BearerAuth: []

  /neo4j/verify:
    post:
      summary: Verify user with JWT token
      tags:
        - Neo4j authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyUserRequest'
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - Invalid or expired token
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Neo4jSignupRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    Neo4jLoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    VerifyUserRequest:
      type: object
      properties:
        authToken:
          type: string
      required:
        - authToken
