openapi: 3.0.0
info:
  title: Neo4j User API
  version: 1.0.0
paths:
  /neo4j/create/user:
    post:
      summary: Create a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User object
          required: true
          schema:
            type: object
      responses:
        '201':
          description: User created successfully
        '401':
          description: Something went wrong with user login

  /neo4j/users:
    get:
      summary: Get all users
      produces:
        - application/json
      responses:
        '200':
          description: List of users
        '401':
          description: Something went wrong with user login

  /neo4j/update/user:
    put:
      summary: Update a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User object
          required: true
          schema:
            type: object
      responses:
        '200':
          description: User updated successfully
        '401':
          description: Something went wrong with user login

  /neo4j/users/{id}:
    get:
      summary: Get user by ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          type: string
      responses:
        '200':
          description: User details retrieved successfully
        '401':
          description: Something went wrong with user login

  /neo4j/deleteUser/{userId}:
    put:
      summary: Delete a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: User ID
          required: true
          type: string
      responses:
        '200':
          description: User deleted successfully
        '401':
          description: Something went wrong with user login
