'use strict';
/*
module.exports = {
  up: async (queryInterface:any, Sequelize:any) => {
    await queryInterface.bulkInsert('books', [
      {
        title: 'The Catcher in the Rye',
        picture: 'catcher-in-the-rye.jpg',
        summary: 'The Catcher in the Rye is a story by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951. It was originally intended for adults but is often read by adolescents for its themes of angst and alienation, and as a critique on superficiality in society. It has been translated widely. Around one million copies are sold each year, with total sales of more than 65 million books.',
        pages: 234,
        amount: 10,
        available_amount: 10,
        author_id: 1,
      },
      {
        title: 'To Kill a Mockingbird',
        picture: 'to-kill-a-mockingbird.jpg',
        summary: 'To Kill a Mockingbird is a novel by Harper Lee published in 1960. Instantly successful, it won the Pulitzer Prize and has become a classic of modern American literature. The plot and characters are loosely based on Lee\'s observations of her family, her neighbors and an event that occurred near her hometown of Monroeville, Alabama, in 1936, when she was 10 years old.',
        pages: 281,
        amount: 15,
        available_amount: 15,
        author_id: 2,
      },
      {
        title: '1984',
        picture: '1984.jpg',
        summary: '1984 is a dystopian novel by George Orwell published in 1949. The novel is set in Airstrip One, a province of the superstate Oceania in a world of perpetual war, omnipresent government surveillance, and public manipulation. The superstate is under the control of the Party, whose leader is Big Brother. The story follows the life of Winston Smith, a low-ranking member of the Party who begins to question his loyalty to Big Brother and the Party agenda.',
        pages: 328,
        amount: 20,
        available_amount: 20,
        author_id: 3,
      },
      {
        title: 'Pride and Prejudice',
        picture: 'pride-and-prejudice.jpg',
        summary: 'Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813. The novel follows the character development of Elizabeth Bennet, who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness. Its humor lies in its honest depiction of manners, education, marriage, and money during the Regency era.',
        pages: 384,
        amount: 18,
        available_amount: 18,
        author_id: 4,
      },
      {
        title: 'The Great Gatsby',
        picture: 'the-great-gatsby.jpg',
        summary: 'The Great Gatsby is a novel written by American author F. Scott Fitzgerald that follows a cast of characters living in the fictional towns of West Egg and East Egg on prosperous Long Island in the summer of 1922. The story primarily concerns the young and mysterious millionaire Jay Gatsby and his quixotic passion and obsession with the beautiful former debutante Daisy Buchanan.',
        pages: 218,
        amount: 22,
        available_amount: 22,
        author_id: 5,
      },
      {
        title: 'Moby-Dick',
        picture: 'moby-dick.jpg',
        summary: 'Moby-Dick; or, The Whale is a novel by Herman Melville that tells the story of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on a giant white sperm whale, Moby Dick, which on a previous voyage destroyed Ahab\'s ship and severed his leg at the knee. The novel was a commercial failure and out of print at the time of the author\'s death in 1891, but during the 20th century, its reputation as a "Great American Novel" was established.',
        pages: 542,
        amount: 14,
        available_amount: 14,
        author_id: 4,
      },
      {
        title: 'Jane Eyre',
        picture: 'jane-eyre.jpg',
        summary: 'Jane Eyre is a novel by English writer Charlotte Brontë, published under the pen name "Currer Bell", on 16 October 1847. Primarily of the Bildungsroman genre, Jane Eyre follows the emotions and experiences of its title character, from her early life as an orphaned girl to her adult life and marriage to Mr. Rochester. The novel has been called "the first historian of the private consciousness" and is one of the most popular and widely read novels in the English language.',
        pages: 366,
        amount: 12,
        available_amount: 12,
        author_id: 2,
      },
      {
        title: 'The Hobbit',
        picture: 'the-hobbit.jpg',
        summary: 'The Hobbit, or There and Back Again is a children\'s fantasy novel by English author J. R. R. Tolkien. It was published on 21 September 1937 to wide critical acclaim, being nominated for the Carnegie Medal and awarded a prize from the New York Herald Tribune for best juvenile fiction. The book remains popular and is recognized as a classic in children\'s literature.',
        pages: 310,
        amount: 16,
        available_amount: 16,
        author_id: 7,
      },
      {
        title: 'Brave New World',
        picture: 'brave-new-world.jpg',
        summary: 'Brave New World is a dystopian social science fiction novel by English author Aldous Huxley, published in 1932. Largely set in a futuristic World State, whose citizens are environmentally engineered into an intelligence-based social hierarchy, the novel anticipates huge scientific advancements in reproductive technology, sleep-learning, psychological manipulation, and classical conditioning, to name a few.',
        pages: 325,
        amount: 11,
        available_amount: 11,
        author_id: 11,
      },
      {
        title: 'The Lord of the Rings',
        picture: 'the-lord-of-the-rings.jpg',
        summary: 'The Lord of the Rings is an epic high-fantasy novel by the English author and scholar J. R. R. Tolkien. Set in Middle-earth, the world at some distant time in the past, the story began as a sequel to Tolkien\'s 1937 children\'s book The Hobbit, but eventually developed into a much larger work. The story is about the power and consequences of a magical ring.',
        pages: 1008,
        amount: 25,
        available_amount: 25,
        author_id: 5,
      },
      {
        title: 'Crime and Punishment',
        picture: 'crime-and-punishment.jpg',
        summary: 'Crime and Punishment is a novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866. It is the second of Dostoevsky\'s full-length novels following his return from ten years of exile in Siberia. The novel focuses on the moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in St. Petersburg who formulates a plan to kill an unscrupulous pawnbroker for her money.',
        pages: 671,
        amount: 10,
        available_amount: 10,
        author_id: 1,
      },
      {
        title: 'The Odyssey',
        picture: 'the-odyssey.jpg',
        summary: 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer. It is one of the oldest extant works of Western literature, and it is an epic poem dealing with themes of love, jealousy, and revenge. The story of Odysseus\' adventures has been used by writers and artists throughout the ages, with the most famous modern adaptations being James Joyce\'s Ulysses and the Coen Brothers\' film O Brother, Where Art Thou?.',
        pages: 424,
        amount: 15,
        available_amount: 15,
        author_id: 2,
      },
      {
        title: 'Frankenstein',
        picture: 'frankenstein.jpg',
        summary: 'Frankenstein; or, The Modern Prometheus is a novel written by English author Mary Shelley that tells the story of Victor Frankenstein, a young scientist who creates a hideous sapient creature in an unorthodox scientific experiment. Shelley started writing the story when she was 18, and the first edition was published anonymously in London on January 1, 1818.',
        pages: 280,
        amount: 12,
        available_amount: 12,
        author_id: 3,
      },
      {
        title: 'The Picture of Dorian Gray',
        picture: 'the-picture-of-dorian-gray.jpg',
        summary: 'The Picture of Dorian Gray is a philosophical novel by Oscar Wilde, first published in complete form in the July 1890 issue of Lippincott\'s Monthly Magazine. The magazine\'s editors feared the story was indecent as submitted, so they censored roughly 500 words without Wilde\'s knowledge. The novel tells the story of Dorian Gray, the young man who sells his soul to remain young and handsome, while his portrait ages and bears the markings of his sins.',
        pages: 253,
        amount: 20,
        available_amount: 20,
        author_id: 4,
      },
      {
        title: 'One Hundred Years of Solitude',
        picture: 'one-hundred-years-of-solitude.jpg',
        summary: 'One Hundred Years of Solitude is a landmark 1967 novel by Colombian author Gabriel García Márquez. The book is a key work in the Latin American literary "boom," which was partially responsible for Márquez\'s Nobel Prize win. It is often cited as one of the greatest achievements in literature in the 20th century. The novel tells the story of the Buendía family, and it is a rich and brilliant chronicle of life and death, and the tragicomedy of humankind.',
        pages: 417,
        amount: 18,
        available_amount: 18,
        author_id: 5,
      },
      {
        title: 'The Alchemist',
        picture: 'the-alchemist.jpg',
        summary: 'The Alchemist (Portuguese: O Alquimista) is a novel by Brazilian author Paulo Coelho that was first published in 1988. Originally written in Portuguese, it became a widely translated international bestseller. The novel details a young Andalusian shepherd named Santiago who yearns to travel in search of a worldly treasure as extravagant as any ever found.',
        pages: 197,
        amount: 14,
        available_amount: 14,
        author_id: 1,
      },
      {
        title: 'Dracula',
        picture: 'dracula.jpg',
        summary: 'Dracula is an 1897 Gothic horror novel by Irish author Bram Stoker. It introduced the character of Count Dracula and established many conventions of subsequent vampire fantasy. The novel tells the story of Dracula\'s attempt to move from Transylvania to England so that he may find new blood and spread the undead curse, and of the battle between Dracula and a small group of people led by Professor Abraham Van Helsing.',
        pages: 418,
        amount: 11,
        available_amount: 11,
        author_id: 2,
      },
  {
    title: 'The Little Prince',
    picture: 'the-little-prince.jpg',
    summary: 'The Little Prince is a novella and the most famous work of the French writer and aviator Antoine de Saint-Exupéry. The book tells the story of a young prince who travels from planet to planet, meeting various inhabitants, and learning valuable life lessons along the way.',
    pages: 96,
    amount: 10,
    available_amount: 10,
    author_id: 5,
  },
  {
    title: 'The Catcher in the Rye',
    picture: 'the-catcher-in-the-rye.jpg',
    summary: 'The Catcher in the Rye is a novel by J.D. Salinger, published in 1951. The story is narrated by Holden Caulfield, a teenager who is one of the most famous and recognizable characters in modern literature. It deals with complex issues of identity, belonging, and growing up.',
    pages: 277,
    amount: 9,
    available_amount: 9,
    author_id: 2,
  },
  {
    title: 'Siddhartha',
    picture: 'siddhartha.jpg',
    summary: 'Siddhartha is a novel by Hermann Hesse, published in 1922. It tells the story of Siddhartha, a young man in ancient India who embarks on a spiritual journey to find enlightenment. The novel explores themes of self-discovery, spirituality, and the search for meaning in life.',
    pages: 121,
    amount: 11,
    available_amount: 11,
    author_id: 3,
  },
  {
    title: 'The Stranger',
    picture: 'the-stranger.jpg',
    summary: 'The Stranger is a novel by Albert Camus, first published in 1942. It tells the story of Meursault, an emotionally detached French Algerian who commits an unpremeditated murder. The novel is often considered an important work of existentialist literature.',
    pages: 123,
    amount: 8,
    available_amount: 8,
    author_id: 4,
  },
  {
    title: 'The Road',
    picture: 'the-road.jpg',
    summary: 'The Road is a post-apocalyptic novel by Cormac McCarthy, published in 2006. The story follows a father and son as they journey through a desolate, destroyed world, trying to survive while maintaining their humanity.',
    pages: 287,
    amount: 7,
    available_amount: 7,
    author_id: 1,
  },
  {
    title: 'Brave New World',
    picture: 'brave-new-world.jpg',
    summary: 'Brave New World is a dystopian novel by Aldous Huxley, published in 1932. It envisions a future society driven by technology, mass production, and mass consumption, where individuality and freedom are sacrificed for stability and happiness.',
    pages: 236,
    amount: 6,
    available_amount: 6,
    author_id: 2,
  },
  {
    title: 'The Name of the Wind',
    picture: 'the-name-of-the-wind.jpg',
    summary: 'The Name of the Wind is a fantasy novel by Patrick Rothfuss, published in 2007. It follows the life of Kvothe, a gifted musician, and magician who grows up to become a legendary figure in a world of magic and intrigue.',
    pages: 662,
    amount: 7,
    available_amount: 7,
    author_id: 3,
  },
  {
    title: 'The Wind-Up Bird Chronicle',
    picture: 'the-wind-up-bird-chronicle.jpg',
    summary: "'The Wind-Up Bird Chronicle is a novel by Haruki Murakami, published in 1994-1995. The book blends the real and the surreal in the story of a man's quest to find his missing wife and confront the mysteries of his own past.'",
    pages: 607,
    amount: 8,
    available_amount: 8,
    author_id: 4,
  },
  {
    title: 'Infinite Jest',
    picture: 'infinite-jest.jpg',
    summary: 'Infinite Jest is a novel by David Foster Wallace, published in 1996. The story is set in a near-future world and explores themes of addiction, entertainment, and the pursuit of happiness. It is known for its complexity and depth.',
    pages: 1079,
    amount: 6,
    available_amount: 6,
    author_id: 5,
  },
  {
    title: 'The Night Circus',
    picture: 'the-night-circus.jpg',
    summary: 'The Night Circus is a fantasy novel by Erin Morgenstern, published in 2011. It tells the story of a magical competition between two young illusionists, Celia and Marco, who are bound by their mentors to a lifelong contest that neither can escape. The circus, Le Cirque des Rêves, serves as the venue for their competition and is open only at night.',
    pages: 387,
    amount: 7,
    available_amount: 7,
    author_id: 1,
  },
    ]);
  },

  down: async (queryInterface:any, Sequelize:any) => {
    await queryInterface.bulkDelete('books', null, {});
  },
};

*/