openapi: 3.0.0
info:
  title: Book API
  version: 1.0.0
paths:
  /mongo/books:
    get:
      tags:
        - Book
      summary: Get all books
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: []
  /mongo/books/{id}:
    get:
      tags:
        - Book
      summary: Get book by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Book ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
  /mongo/book/create:
    post:
      tags:
        - Book
      summary: Create a new book
      requestBody:
        description: Book data
        required: true
        content:
          application/json:
            example:
              title: "Sample Book"
              picture: "sample.jpg"
              summary: "A sample book description."
              pages: 200
              mount: 10
              available_amount: 10
      responses:
        '200':
          description: Book created successfully
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
  /mongo/book/update/{id}:
    post:
      tags:
        - Book
      summary: Update book by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Book ID
          schema:
            type: string
      requestBody:
        description: Updated book data
        required: true
        content:
          application/json:
            example:
              title: "Updated Book"
              picture: "updated.jpg"
              summary: "An updated book description."
              pages: 250
              mount: 15
              available_amount: 8
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
