openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /mongo/users:
    get:
      tags:
        - Mongo User
      summary: Get all users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: []
  /mongo/user/create:
    post:
      tags:
        - Mongo User
      summary: Create a new user
      requestBody:
        description: User data
        required: true
        content:
          application/json:
            example:
              first_name: John
              last_name: Doe
              email: john.doe@example.com
              password: secret123
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              example: {}
        '409':
          description: Conflict, email already exists
        '500':
          description: Internal Server Error
  /mongo/users/{id}:
    get:
      tags:
        - Mongo User
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
    put:
      tags:
        - Mongo User
      summary: Update user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
      requestBody:
        description: Updated user data
        required: true
        content:
          application/json:
            example:
              first_name: UpdatedFirstName
              last_name: UpdatedLastName
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Mongo User
      summary: Delete user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
