openapi: 3.0.0
info:
  title: Book CRUD API
  description: CRUD operations for managing books
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /mongo/books:
    get:
      summary: Get all books
      tags:
        - Books
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal Server Error

  /mongo/book/create:
    post:
      summary: Create a new book
      tags:
        - Books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRequest'
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal Server Error

components:
  schemas:
    BookRequest:
      type: object
      properties:
        title:
          type: string
        picture:
          type: string
        summary:
          type: string
        pages:
          type: integer
        mount:
          type: integer
        available_amount:
          type: integer
      required:
        - title
        - picture
        - summary
        - pages
        - mount
        - available_amount
