openapi: 3.0.0
info:
  title: Book Review API
  description: APIs related to book reviews
  version: 1.0.0
tags:
  - name: Reviews
    description: APIs related to book reviews
paths:
  /mongo/reviews:
    get:
      summary: Get all reviews
      tags: 
        - Reviews
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - _id: "review_id"
                  review_data:
                    stars: 4
                    user_id: "user_id"
                    book_id: "book_id"
  /mongo/review/create:
    post:
      summary: Create a new review
      tags: 
        - Reviews
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stars:
                  type: integer
                user_id:
                  type: string
                book_id:
                  type: string
              required:
                - stars
                - user_id
                - book_id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: "review_id"
                review_data:
                  stars: 4
                  user_id: "user_id"
                  book_id: "book_id"
  /mongo/review/update:
    post:
      summary: Update an existing review
      tags: 
        - Reviews
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                stars:
                  type: integer
                user_id:
                  type: string
                book_id:
                  type: string
              required:
                - id
                - stars
                - user_id
                - book_id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: "review_id"
                review_data:
                  stars: 4
                  user_id: "user_id"
                  book_id: "book_id"
