openapi: 3.0.0
info:
  title: Review API
  description: API for managing reviews
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /mongo/reviews:
    get:
      summary: Get all reviews
      tags:
        - Reviews
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                - _id: "60a2c1d8e43a1a001cfc1db0"
                  review_data:
                    stars: 5
                    user_id: 123
                    book_id: 456
                  createdAt: "2022-05-17T10:30:00.000Z"
                  updatedAt: "2022-05-17T10:30:00.000Z"
        '500':
          description: Internal Server Error
  
  /mongo/review/create:
    post:
      summary: Create a review
      tags:
        - Reviews
      requestBody:
        required: true
        content:
          application/json:
            example:
              - stars: 5
                user_id: 123
                book_id: 456
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                - _id: "60a2c1d8e43a1a001cfc1db0"
                  review_data:
                    stars: 5
                    user_id: 123
                    book_id: 456
                  createdAt: "2022-05-17T10:30:00.000Z"
                  updatedAt: "2022-05-17T10:30:00.000Z"
        '500':
          description: Internal Server Error
