openapi: 3.0.0
info:
  title: Review API
  version: 1.0.0
paths:
  /mongo/reviews:
    get:
      tags:
        - Mongo Review
      summary: Get all reviews
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: []
        '500':
          description: Internal Server Error
  /mongo/review/create:
    post:
      tags:
        - Mongo Review
      summary: Create a new review
      requestBody:
        description: Review data
        required: true
        content:
          application/json:
            example:
              stars: 4
              user_id: 123
              book_id: 456
      responses:
        '200':
          description: Review created successfully
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
  /mongo/review/update:
    post:
      tags:
        - Mongo Review
      summary: Update review
      requestBody:
        description: Updated review data
        required: true
        content:
          application/json:
            example:
              id: "review_id_here"
              stars: 5
              user_id: 789
              book_id: 101
      responses:
        '200':
          description: Review updated successfully
          content:
            application/json:
              example: {}
        '500':
          description: Internal Server Error
