name: Auto test 

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    env:
      MYSQL_PROD_DB_NAME: ${{ secrets.MYSQL_PROD_DB_NAME }}
      MYSQL_PROD_DB_USERNAME: ${{ secrets.MYSQL_PROD_DB_USERNAME }}
      MYSQL_PROD_DB_PASSWORD: ${{ secrets.MYSQL_PROD_DB_PASSWORD }}
      MYSQL_PROD_DB_HOST: ${{ secrets.MYSQL_PROD_DB_HOST }}
      MYSQL_PROD_DB_PORT: ${{ secrets.MYSQL_PROD_DB_PORT }}
      MONGO_PROD_DB_NAME: ${{ secrets.MONGO_PROD_DB_NAME }}
      MONGO_PROD_DB_HOST: ${{ secrets.MONGO_PROD_DB_HOST }}
      NEO4J_PROD_DB_HOST: ${{ secrets.NEO4J_PROD_DB_HOST }}
      NEO4J_PROD_DB_USERNAME: ${{ secrets.NEO4J_PROD_DB_USERNAME }}
      NEO4J_PROD_DB_PASSWORD: ${{ secrets.NEO4J_PROD_DB_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
